export const config = {
  ledMac: "BE:27:F9:00:97:65",
  namePrefixes: ["ELK-BLE", "MELK", "LEDBLE", "LED-"],
  debug: true,
  discoveryTimeoutMs: 5000,
  discoveryPollMs: 200,
  connectTimeoutMs: 5000,
  connectRetriesPerSighting: 3,
  connectBudgetMs: 120000,
  retryDelayMs: 1000,
  gattTimeoutMs: 10000,
  searchBudgetMs: 60000,
  discoveryRefreshMs: 15000,
  discoveryStopDelayMs: 300,
  discoveryResetDelayMs: 800,
  discoveryPowerToggleMax: 1,
  offlineStreakPolls: 4,
  daemonSocketPath: "/tmp/ELK-JS.sock",
  daemonPidFile: "/tmp/ELK-JS.pid",
  daemonLogFile: "/tmp/ELK-JS.log",
  daemonStartTimeoutMs: 10000,
  daemonRequestTimeoutMs: 10000,
};
